# Generated by Django 4.2.13 on 2024-05-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_type_alter_proj_cert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='proj_cert',
            name='url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
